version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato
    ports:
      - 3308:3308
    networks:
     - AppNet

  spring-boot:
    image: nourhenekheriji/springback
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - AppNet
    restart: on-failure
  angular:
    image: nourhenekheriji/angular
    container_name: angular
    ports:
      - 80:80
    depends_on:
      - spring-boot
    networks:
      - AppNet

networks:
  AppNet:


