version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato
    ports:
      - 3308:3308

  angular:
    image: nourhenekheriji/angular
    container_name: angular
    ports:
      - 80:80
    depends_on:
      - database



